version: "3.9"

services:
  go-gateway:
    container_name: go-gateway
    build:
      context: ./app/ms-gateway
      dockerfile: Dockerfile_dev
    ports:
      - "8181:8080"
      - "2345:2345"
    environment:
      GOTRACEBACK: all
    volumes:
      - ./app/ms-gateway:/app

    env_file:
      - ./app/ms-gateway/.env.dev
    depends_on:
      - go-mongodb

  go-mongodb:
    image: mongo:4-focal
    container_name: go-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Password1
      MONGO_USERNAME: users
      MONGO_PASSWORD: password1
      MONGO_HOST: mongodb
    volumes:
      - './init-mongodb.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro'