version: "3.9"

services:
  go-gateway:
    container_name: go-gateway
    build:
      context: ./app/ms-gateway
      dockerfile: Dockerfile_dev
    ports:
      - "8181:8080"
    volumes:
      - ./app/ms-gateway:/app
    environment:
      MONGO_HOST: mongo
    env_file:
      - ./app/ms-gateway/.env.dev
