---
isDebug: true
listen:
  host: 0.0.0.0
  port: 8080
mongo:
  mongo_host: go-api-mongodb
  mongo_port: 27017
  mongo_user: users
  mongo_password: password1
  mongo_database: users
  mongo_uri_scheme: mongodb