FROM golang:1.20-alpine

# Set destination for COPY
WORKDIR /app

# Install "air"
RUN go install github.com/cosmtrek/air@latest

# Install Delve debugger
RUN go install github.com/go-delve/delve/cmd/dlv@latest

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/engine/reference/builder/#copy
COPY . .

# Optional:
# To bind to a TCP port, runtime parameters must be supplied to the docker command.
# But we can document in the Dockerfile what ports
# the application is going to listen on by default.
# https://docs.docker.com/engine/reference/builder/#expose
EXPOSE 2345 8080

# Run
CMD ["air", "-c", ".air.toml"]
